# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(628, 762)
        AddWindow.setStyleSheet("background-color: #A4A8A6;\n"
"")
        self.label_subject = QtWidgets.QLabel(AddWindow)
        self.label_subject.setGeometry(QtCore.QRect(-10, 280, 641, 51))
        self.label_subject.setStyleSheet("color:white;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"border: 1px solid;\n"
"background-color: #06A310;")
        self.label_subject.setAlignment(QtCore.Qt.AlignCenter)
        self.label_subject.setObjectName("label_subject")
        self.btn_back = QtWidgets.QPushButton(AddWindow)
        self.btn_back.setGeometry(QtCore.QRect(50, 680, 161, 51))
        self.btn_back.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.btn_add = QtWidgets.QPushButton(AddWindow)
        self.btn_add.setGeometry(QtCore.QRect(410, 680, 161, 51))
        self.btn_add.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.txt_question = QtWidgets.QTextEdit(AddWindow)
        self.txt_question.setGeometry(QtCore.QRect(170, 350, 381, 131))
        self.txt_question.setStyleSheet("background-color:#FFF5B2;\n"
"border-radius:5px;\n"
"border: 1px groove;\n"
"border-color: #FFCF38;\n"
"font-size: 15px;")
        self.txt_question.setObjectName("txt_question")
        self.txt_answer = QtWidgets.QTextEdit(AddWindow)
        self.txt_answer.setGeometry(QtCore.QRect(170, 520, 381, 111))
        self.txt_answer.setStyleSheet("background-color:#FFF5B2;\n"
"border-radius:5px;\n"
"border: 1px groove;\n"
"border-color: #FFCF38;\n"
"font-size: 15px;")
        self.txt_answer.setObjectName("txt_answer")
        self.label_question = QtWidgets.QLabel(AddWindow)
        self.label_question.setGeometry(QtCore.QRect(50, 370, 101, 91))
        self.label_question.setText("")
        self.label_question.setPixmap(QtGui.QPixmap("images/question icon.png"))
        self.label_question.setScaledContents(True)
        self.label_question.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_question.setObjectName("label_question")
        self.label_answer = QtWidgets.QLabel(AddWindow)
        self.label_answer.setGeometry(QtCore.QRect(50, 530, 101, 91))
        self.label_answer.setText("")
        self.label_answer.setPixmap(QtGui.QPixmap("images/answer icon.png"))
        self.label_answer.setScaledContents(True)
        self.label_answer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_answer.setObjectName("label_answer")
        self.label_error = QtWidgets.QLabel(AddWindow)
        self.label_error.setGeometry(QtCore.QRect(20, 640, 611, 20))
        self.label_error.setStyleSheet("color: #FF0000;\n"
"font-size: 12px;\n"
"font-weight: bold;\n"
"")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.label = QtWidgets.QLabel(AddWindow)
        self.label.setGeometry(QtCore.QRect(120, -10, 411, 291))
        self.label.setStyleSheet("background-color: #e9e9e9;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/questions_answers.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_bg = QtWidgets.QLabel(AddWindow)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 631, 281))
        self.label_bg.setStyleSheet("background-color: #e9e9e9;")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.label_bg.raise_()
        self.label.raise_()
        self.label_subject.raise_()
        self.btn_back.raise_()
        self.btn_add.raise_()
        self.txt_question.raise_()
        self.txt_answer.raise_()
        self.label_question.raise_()
        self.label_answer.raise_()
        self.label_error.raise_()

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "Dialog"))
        self.label_subject.setText(_translate("AddWindow", "SUBJECT : <name>"))
        self.btn_back.setText(_translate("AddWindow", "<< BACK"))
        self.btn_add.setText(_translate("AddWindow", "Add Question"))
        self.txt_question.setPlaceholderText(_translate("AddWindow", "Write the question here"))
        self.txt_answer.setPlaceholderText(_translate("AddWindow", "Write the answer here"))
        self.label_error.setText(_translate("AddWindow", "ERROR LABEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddWindow = QtWidgets.QDialog()
    ui = Ui_AddWindow()
    ui.setupUi(AddWindow)
    AddWindow.show()
    sys.exit(app.exec_())
