# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnswerDialog(object):
    def setupUi(self, AnswerDialog):
        AnswerDialog.setObjectName("AnswerDialog")
        AnswerDialog.resize(400, 300)
        AnswerDialog.setStyleSheet("background-color: #A4A8A6;")
        self.btn_ok = QtWidgets.QPushButton(AnswerDialog)
        self.btn_ok.setGeometry(QtCore.QRect(90, 220, 231, 51))
        self.btn_ok.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_ok.setObjectName("btn_ok")
        self.label_answer = QtWidgets.QLabel(AnswerDialog)
        self.label_answer.setGeometry(QtCore.QRect(0, 80, 401, 111))
        self.label_answer.setStyleSheet("font-size : 15px;\n"
"color: #0048FF;\n"
"\n"
"font-weight: bold;\n"
"border-color: #95FF93;\n"
"background-color: #e9e9e9;")
        self.label_answer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_answer.setWordWrap(True)
        self.label_answer.setObjectName("label_answer")
        self.label_title = QtWidgets.QLabel(AnswerDialog)
        self.label_title.setGeometry(QtCore.QRect(-120, 0, 641, 51))
        self.label_title.setStyleSheet("color:white;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"border: 1px solid;\n"
"background-color: #06A310;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")

        self.retranslateUi(AnswerDialog)
        QtCore.QMetaObject.connectSlotsByName(AnswerDialog)

    def retranslateUi(self, AnswerDialog):
        _translate = QtCore.QCoreApplication.translate
        AnswerDialog.setWindowTitle(_translate("AnswerDialog", "Dialog"))
        self.btn_ok.setText(_translate("AnswerDialog", "OK"))
        self.label_answer.setText(_translate("AnswerDialog", "TextLabel"))
        self.label_title.setText(_translate("AnswerDialog", "A N S W E R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnswerDialog = QtWidgets.QDialog()
    ui = Ui_AnswerDialog()
    ui.setupUi(AnswerDialog)
    AnswerDialog.show()
    sys.exit(app.exec_())
