# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 763)
        MainWindow.setStyleSheet("background-color: #A4A8A6;")
        self.label_error = QtWidgets.QLabel(MainWindow)
        self.label_error.setGeometry(QtCore.QRect(50, 640, 521, 21))
        self.label_error.setStyleSheet("color: #FF0000;\n"
"font-size: 12px;\n"
"font-weight: bold;\n"
"")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.combobox_subj = QtWidgets.QComboBox(MainWindow)
        self.combobox_subj.setGeometry(QtCore.QRect(50, 590, 521, 31))
        self.combobox_subj.setStyleSheet("background-color:#FFF5B2;\n"
"border-radius:5px;\n"
"border: 1px groove;\n"
"border-color: #FFCF38;\n"
"font-size: 15px;")
        self.combobox_subj.setObjectName("combobox_subj")
        self.btn_add = QtWidgets.QPushButton(MainWindow)
        self.btn_add.setGeometry(QtCore.QRect(410, 510, 161, 51))
        self.btn_add.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.label_title = QtWidgets.QLabel(MainWindow)
        self.label_title.setGeometry(QtCore.QRect(-10, 370, 641, 51))
        self.label_title.setStyleSheet("color:white;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"border: 1px solid;\n"
"background-color: #06A310;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.btn_load = QtWidgets.QPushButton(MainWindow)
        self.btn_load.setGeometry(QtCore.QRect(50, 680, 161, 51))
        self.btn_load.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_load.setObjectName("btn_load")
        self.btn_delete = QtWidgets.QPushButton(MainWindow)
        self.btn_delete.setGeometry(QtCore.QRect(410, 680, 161, 51))
        self.btn_delete.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.txt_subj = QtWidgets.QLineEdit(MainWindow)
        self.txt_subj.setGeometry(QtCore.QRect(50, 470, 521, 31))
        self.txt_subj.setStyleSheet("background-color:#FFF5B2;\n"
"border-radius:5px;\n"
"border: 1px groove;\n"
"border-color: #FFCF38;\n"
"font-size: 15px;")
        self.txt_subj.setObjectName("txt_subj")
        self.label_subjects = QtWidgets.QLabel(MainWindow)
        self.label_subjects.setGeometry(QtCore.QRect(50, 560, 161, 21))
        self.label_subjects.setStyleSheet("font-size : 15px;\n"
"color: #0048FF;\n"
"\n"
"font-weight: bold;\n"
"border-color: #95FF93;")
        self.label_subjects.setObjectName("label_subjects")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(110, -20, 401, 421))
        self.label.setStyleSheet("background-color: #e9e9e9;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/reader-310398.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_bg = QtWidgets.QLabel(MainWindow)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 631, 391))
        self.label_bg.setStyleSheet("background-color: #e9e9e9;")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.label_add = QtWidgets.QLabel(MainWindow)
        self.label_add.setGeometry(QtCore.QRect(50, 440, 161, 21))
        self.label_add.setStyleSheet("font-size : 15px;\n"
"color: #0048FF;\n"
"\n"
"font-weight: bold;\n"
"border-color: #95FF93;")
        self.label_add.setObjectName("label_add")
        self.label_bg.raise_()
        self.label.raise_()
        self.label_error.raise_()
        self.combobox_subj.raise_()
        self.btn_add.raise_()
        self.label_title.raise_()
        self.btn_load.raise_()
        self.btn_delete.raise_()
        self.txt_subj.raise_()
        self.label_subjects.raise_()
        self.label_add.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label_error.setText(_translate("MainWindow", "LABEL ERROR"))
        self.btn_add.setText(_translate("MainWindow", "A D D"))
        self.label_title.setText(_translate("MainWindow", "R E V I E W E R"))
        self.btn_load.setText(_translate("MainWindow", "Load Subject"))
        self.btn_delete.setText(_translate("MainWindow", "Delete Subject"))
        self.txt_subj.setPlaceholderText(_translate("MainWindow", " Enter a New Subject here then click \"ADD\" "))
        self.label_subjects.setText(_translate("MainWindow", "  CHOOSE SUBJECT"))
        self.label_add.setText(_translate("MainWindow", "  ADD SUBJECT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
