# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subjectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubjectWindow(object):
    def setupUi(self, SubjectWindow):
        SubjectWindow.setObjectName("SubjectWindow")
        SubjectWindow.resize(631, 763)
        SubjectWindow.setStyleSheet("background-color: #A4A8A6;")
        self.scroll_qa = QtWidgets.QScrollArea(SubjectWindow)
        self.scroll_qa.setGeometry(QtCore.QRect(0, 120, 631, 541))
        self.scroll_qa.setStyleSheet("background-color:#FFF5B2;\n"
"border: 1px solid;\n"
"border-color: #FFCF38;\n"
"font-size: 15px;")
        self.scroll_qa.setWidgetResizable(True)
        self.scroll_qa.setObjectName("scroll_qa")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 539))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_qa.setWidget(self.scrollAreaWidgetContents)
        self.label_subject = QtWidgets.QLabel(SubjectWindow)
        self.label_subject.setGeometry(QtCore.QRect(-20, 0, 671, 51))
        self.label_subject.setStyleSheet("color:white;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"border: 1px solid;\n"
"background-color: #06A310;")
        self.label_subject.setAlignment(QtCore.Qt.AlignCenter)
        self.label_subject.setObjectName("label_subject")
        self.label_delete_col = QtWidgets.QLabel(SubjectWindow)
        self.label_delete_col.setGeometry(QtCore.QRect(420, 90, 271, 21))
        self.label_delete_col.setStyleSheet("color: #0048FF;\n"
"font-size: 12px;\n"
"font-weight: bold;\n"
"")
        self.label_delete_col.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delete_col.setObjectName("label_delete_col")
        self.label_subj_col = QtWidgets.QLabel(SubjectWindow)
        self.label_subj_col.setGeometry(QtCore.QRect(0, 90, 161, 21))
        self.label_subj_col.setStyleSheet("color: #0048FF;\n"
"font-size: 12px;\n"
"font-weight: bold;")
        self.label_subj_col.setAlignment(QtCore.Qt.AlignCenter)
        self.label_subj_col.setObjectName("label_subj_col")
        self.label_instructions = QtWidgets.QLabel(SubjectWindow)
        self.label_instructions.setGeometry(QtCore.QRect(30, 60, 631, 21))
        self.label_instructions.setStyleSheet("color: white;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"")
        self.label_instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_instructions.setObjectName("label_instructions")
        self.info_icon = QtWidgets.QLabel(SubjectWindow)
        self.info_icon.setGeometry(QtCore.QRect(160, 60, 31, 21))
        self.info_icon.setText("")
        self.info_icon.setPixmap(QtGui.QPixmap("images/info icon.png"))
        self.info_icon.setScaledContents(True)
        self.info_icon.setObjectName("info_icon")
        self.btn_back = QtWidgets.QPushButton(SubjectWindow)
        self.btn_back.setGeometry(QtCore.QRect(50, 680, 161, 51))
        self.btn_back.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.btn_add = QtWidgets.QPushButton(SubjectWindow)
        self.btn_add.setGeometry(QtCore.QRect(410, 680, 161, 51))
        self.btn_add.setStyleSheet("QPushButton\n"
"{\n"
"font-size : 15px;\n"
"background-color : #05BF11;\n"
"color: \"white\";\n"
"font-weight: bold;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color: #95FF93;\n"
"}\n"
"\n"
" QPushButton:hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(SubjectWindow)
        QtCore.QMetaObject.connectSlotsByName(SubjectWindow)

    def retranslateUi(self, SubjectWindow):
        _translate = QtCore.QCoreApplication.translate
        SubjectWindow.setWindowTitle(_translate("SubjectWindow", "Dialog"))
        self.label_subject.setText(_translate("SubjectWindow", "SUBJECT : <name>"))
        self.label_delete_col.setText(_translate("SubjectWindow", "DELETE"))
        self.label_subj_col.setText(_translate("SubjectWindow", "QUESTIONS"))
        self.label_instructions.setText(_translate("SubjectWindow", "Click on the questions to reveal the anwer"))
        self.btn_back.setText(_translate("SubjectWindow", "<< BACK"))
        self.btn_add.setText(_translate("SubjectWindow", "Add Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubjectWindow = QtWidgets.QDialog()
    ui = Ui_SubjectWindow()
    ui.setupUi(SubjectWindow)
    SubjectWindow.show()
    sys.exit(app.exec_())
